//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_22._101_Rusheshnikova_authorization1
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int userID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int roleID { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
